DeltaQrCode/ViewModels/Appointments/AppointmentVM.cs
using System;

namespace DeltaQrCode.ViewModels.Appointments
{
    public class AppointmentVM
    {
        public AppointmentVM()
        {

        }
        public AppointmentVM(DateTime appointmentStart)
        {
            DataAppointment = appointmentStart;
            OraInceput = DataAppointment.TimeOfDay;
            StartTime_Hour = OraInceput.Hours;
            StartTime_Minutes = OraInceput.Minutes;

        }

        public int Id { get; set; }
        public int ServiciuId { get; set; }
        public string Serviciu { get; set; }
        public int RampId { get; set; }
        public string NumarInmatriculare { get; set; }
        public string NumeClient { get; set; }
        public string EmailClient { get; set; }
        public string NumarTelefon { get; set; }
        public TimeSpan OraInceput { get; set; }
        public DateTime DataAppointment { get; set; }
        public int DurataInMinute { get; set; }
        public TimeSpan OraSfarsit => OraInceput.Add(new TimeSpan(0, 0, DurataInMinute, 0));
        public bool Confirmed { get; set; }
        public string ConfirmedCode { get; set; }
        public DateTime? ConfirmedDate { get; set; }
        public string Observatii { get; set; }
        public bool ChangedByClient { get; set; }
        public int StartTime_Hour { get; set; }
        public int StartTime_Minutes { get; set; }

    }
}

DeltaQrCode/ViewModels/Appointments/AppointmentsIndexVm.cs
using System.Collections.Generic;

namespace DeltaQrCode.ViewModels.Appointments
{
    public class AppointmentsIndexVm
    {
        public AppointmentsIndexVm(int rampId, List<AppointmentVM> appointments)
        {
            RampId = rampId;
            Appointments = appointments;
        }
        public int RampId { get; set; }
        public List<AppointmentVM> Appointments { get; set; }
    }
}

DeltaQrCode/ViewModels/Appointments/AppointmentsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeltaQrCode.ViewModels.Appointments
{
    public class AppointmentsVM
    {
        public uint Id { get; set; }
        public int? ApptIndex { get; set; }
        public string Serviciu { get; set; }
        public string NrMasina { get; set; }
        public string NumeClient { get; set; }
        public string EmailClient { get; set; }
        public string NrTelefon { get; set; }
        public DateTime DataAppointment { get; set; }
        public string DataIntroducere { get; set; }
        public TimeSpan OraInceput { get; set; }
        public int DurationInMinutes { get; set; }
        public bool Confirmed { get; set; }
        public bool Canceled { get; set; }
        public DateTime? CanceledDate { get; set; }
        public DateTime? ConfirmedDate { get; set; }
        public string Notes { get; set; }
        public int RampId { get; set; }
    }
}

DeltaQrCode/ViewModels/Appointments/CalendarVm.cs
using System;
using System.Collections.Generic;

namespace DeltaQrCode.ViewModels.Appointments
{

    public class CalendarVm
    {
        public List<DateTime> AvailableDates { get; set; }

        public DateTime ActiveDate { get; set; }
    }


}

DeltaQrCode/ViewModels/Appointments/ConfirmVM.cs
namespace DeltaQrCode.ViewModels.Appointments
{
    public class ConfirmVM
    {

        public ConfirmVM()
        {

        }
        public ConfirmVM(int id, bool confirm)
        {
            Id = id;
            Confirm = confirm;
        }

        public int Id { get; set; }
        public bool Confirm { get; set; }
    }
}

DeltaQrCode/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DeltaQrCode.Controllers
{
    using System.IO;
    using AutoMapper;
    using ClosedXML.Excel;
    using DeltaQrCode.HelpersAndExtensions;
    using DeltaQrCode.ModelsDto;
    using DeltaQrCode.Services;
    using DeltaQrCode.ViewModels.Appointments;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Newtonsoft.Json;
    using Serilog;

    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly IAppointmentService _appointmentService;
        private readonly IMapper _mapper;

        public AppointmentsController(IAppointmentService appointmentService, IMapper mapper)
        {
            _appointmentService = appointmentService;
            _mapper = mapper;
        }


        public ActionResult Index(string startDateString, string activeDateString)
        {
            CalendarVm calendarVm = new CalendarVm();
            var startDate = Helpers.GetStartDateFromStringParam(startDateString);
            var activeDate = Helpers.GetStartDateFromStringParam(activeDateString);

            if (startDate < DateTime.Now) startDate = DateTime.Now;
            if (activeDate < startDate) activeDate = startDate;

            if (activeDate.Date > startDate.Date.AddDays(3))
            {
                startDate = activeDate.AddDays(-2);
            }

            calendarVm.AvailableDates = Helpers.CreateAvailableDatesList(startDate);
            calendarVm.ActiveDate = activeDate;

            return View(calendarVm);
        }




        public async Task<JsonResult> GetAppointmentsForDate(string apptDate)
        {
            DateTime dt;
            DateTime.TryParse(apptDate, out dt);
            if (dt == new DateTime())
                dt = DateTime.Now.Date;
            var appointmentsList = await _appointmentService.GetAppointmentsAsync(dt);
            if (appointmentsList.Entity == null)
            {
                return new JsonResult(new List<AppointmentsIndexVm>());
            }

            var rampIds = appointmentsList.Entity.Select(x => x.RampId).Distinct();
            var result = new List<AppointmentsIndexVm>();
            foreach (var item in rampIds)
            {
                var list = appointmentsList.Entity.Where(x => x.RampId == item).ToList();
                var mappedList = _mapper.Map<List<AppointmentVM>>(list);
                var aux = new AppointmentsIndexVm(item, mappedList);
                result.Add(aux);
            }

            return new JsonResult(result);
        }


        [HttpGet]
        public async Task<IActionResult> ModalEdit(int id)
        {
            var hours = new List<SelectListItem>();
            for (int i = 8; i <= 17; i++)
            {
                hours.Add(new SelectListItem(i.ToString(), i.ToString()));
            }
            SelectList s1 = new SelectList(hours, "Value", "Text");
            ViewBag.hours = s1;


            var minutes = new List<SelectListItem>() { new SelectListItem(0.ToString(), 0.ToString()), new SelectListItem(30.ToString(), 30.ToString()) };

            SelectList s2 = new SelectList(minutes, "Value", "Text");
            ViewBag.minutes = s2;

            var appt = await _appointmentService.GetAppointmentByIdAsync(id);
            var appointment = _mapper.Map<AppointmentVM>(appt.Entity);

            return PartialView("_EditAppointmentPartial", appointment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAppt(AppointmentVM appt)
        {
            try
            {
                appt.OraInceput = TimeSpan.FromMinutes(appt.StartTime_Hour * 60 + appt.StartTime_Minutes);
                appt.DataAppointment.AddHours(appt.StartTime_Hour).AddMinutes(appt.StartTime_Minutes);

                var dto = _mapper.Map<AppointmentDto>(appt);
                var result = await _appointmentService.UpdateAppointmentAsync(dto);

                if (result.Successful)
                {
                    return Ok(JsonConvert.SerializeObject("Programarea a fost editata cu succes!"));
                }

                return BadRequest("Ceva nu a mers bine la editarea programarii in controller!");

            }
            catch (Exception e)
            {
                Log.Error(e, "Ceva nu a mers bine la editarea programarii in controller!");
                return BadRequest("Ceva nu a mers bine la editarea programarii in controller!");
            }
        }


        [HttpGet]
        public IActionResult ModalAdd(string startDateStr, string startHour, string rampId)
        {

            var hours = new List<SelectListItem>();
            for (int i = 8; i <= 17; i++)
            {
                hours.Add(new SelectListItem(i.ToString(), i.ToString()));
            }
            SelectList s1 = new SelectList(hours, "Value", "Text");
            ViewBag.hours = s1;


            var minutes = new List<SelectListItem>() { new SelectListItem(0.ToString(), 0.ToString()), new SelectListItem(30.ToString(), 30.ToString()) };

            SelectList s2 = new SelectList(minutes, "Value", "Text");
            ViewBag.minutes = s2;

            DateTime startDate = DateTime.Parse(startDateStr);
            var s = startHour.Split('_');
            DateTime appointmentStart = startDate.AddHours(int.Parse(s[0])).AddMinutes(int.Parse(s[1]));

            var appointment = new AppointmentVM(appointmentStart);
            appointment.RampId = int.Parse(rampId);


            return PartialView("_AddAppointmentPartial", appointment);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAppt(AppointmentVM appt)
        {
            try
            {
                appt.OraInceput = new TimeSpan(appt.StartTime_Hour, appt.StartTime_Minutes, 0);
                var model = _mapper.Map<AppointmentDto>(appt);
                var result = await _appointmentService.AddAppointmentAsync(model);

                if (result.Successful)
                {
                    return Ok(JsonConvert.SerializeObject("Programarea a fost adaugata!"));

                }

                return BadRequest("Ceva nu a mers bine la adaugarea programarii in controller!");
            }
            catch (Exception e)
            {
                Log.Error(e, "Ceva nu a mers bine la adaugarea programarii in controller!");
                return BadRequest("Ceva nu a mers bine la adaugarea programarii in controller!");
            }
        }


        [HttpGet]
        public IActionResult DeleteModal(int id)
        {
            return PartialView("_DeleteAppointmentPartial", id);
        }



        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            try
            {
                var result = await _appointmentService.DeleteAppointmentAsync(id);

                if (result.Successful)
                {
                    return Ok(JsonConvert.SerializeObject("Programarea a fost stearsa!"));
                }

                return BadRequest("Ceva nu a mers bine la stergerea programarii in controller!");
            }
            catch (Exception e)
            {
                Log.Error(e, "Ceva nu a mers bine la stergerea programarii in controller!");
                return BadRequest("Ceva nu a mers bine la stergerea programarii in controller!");
            }

        }


        [HttpGet]
        public IActionResult ConfirmModal(int id, bool confirm)
        {
            return PartialView("_ConfirmAppointmentPartial", new ConfirmVM(id, confirm));
        }


        [HttpPost]
        public async Task<IActionResult> ConfirmAppt(int id, bool confirm)
        {
            try
            {
                var result = await _appointmentService.ConfirmAppointmentAsync(id, confirm);

                if (result.Successful)
                {
                    var message = "Programarea a fost confirmata!";
                    if (!result.Entity.Confirmed)
                    {
                        message = "A fost anulata confirmarea programarii!";
                    }
                    return Ok(JsonConvert.SerializeObject(message));
                }

                return BadRequest("Ceva nu a mers bine la confirmarea programarii in controller!");
            }
            catch (Exception e)
            {
                Log.Error(e, "Ceva nu a mers bine la confirmarea programarii in controller!");
                return BadRequest("Ceva nu a mers bine la confirmarea programarii in controller!");
            }

        }


        [HttpGet]
        public IActionResult MenuModal(int id, bool confirm)
        {
            return PartialView("_MenuAppointmentPartial", new ConfirmVM(id, !confirm));
        }


        [HttpGet]
        public async Task<ActionResult> InfoModal(int id)
        {
            var appt = await _appointmentService.GetAppointmentByIdAsync(id);
            var appointment = _mapper.Map<AppointmentVM>(appt.Entity);

            return PartialView("_InfoAppointmentPartial", appointment);
        }


        [HttpGet]
        [Produces("application/json")]
        public IActionResult GetTipServiciu()
        {
            var list = new List<string>();
            list.Add(ServiceType.Mecanica.ToDisplayString());
            list.Add(ServiceType.Vulcanizare.ToDisplayString());
            return new JsonResult(list);
        }


        [HttpGet]
        [Produces("application/json")]
        public IActionResult GetTimeDictionary()
        {
            return new JsonResult(ConstantsAndEnums.TimeDictionary);
        }


        [HttpGet]
        [Produces("application/json")]

DeltaQrCode/Views/Appointments/Index.cshtml
@using System.Security.Cryptography.X509Certificates
@model DeltaQrCode.ViewModels.Appointments.CalendarVm

@{
    ViewBag.Title = "Calendar";
}
<head>
    <link href="~/css/SchedulerIndexStyle.css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdn.rawgit.com/asvd/dragscroll/master/dragscroll.js"></script>
</head>

<div id="HeaderAlert" class="alert" role="alert">
</div>

@*<input type="text" id="ApptState" value="0" hidden="hidden" />*@

<div class="container">
    <div class="form-row">
        <div class="input-group col-sm-10 col-md-8 col-10 col-lg-6">
            <label class="col-form-label"></label>
            <input id="datepicker" class="form-control" placeholder="Selecteaza data" />
            <span class="text-danger"></span>
            <button style="margin-left:10px;" id="DownloadZi" onclick="ondownload()" class="btn btn-info text-white">Raport Luna <i class="fas fa-file-download"></i></button>
            <a style="margin-left:10px;" type="button" id="DownloadTotal" asp-action="download" asp-controller="Appointments" class="btn btn-secondary">Raport Total <i class="fas fa-file-download"></i></a>

        </div>
    </div>
</div>
<br />
<div>
    <div class="row">
        @for (int rampNr = 1; rampNr < 5; rampNr++)
        {
            <partial model="@rampNr" name="_RampPartial" />
        }
    </div>
</div>
<!--  this is the modal dialog that will house the partial content-->
<div id="myApptModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="partialInfo"></div>
        </div>
    </div>
</div>
<div id="myApptMenuModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myMenuModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content text-center" style="max-width:800px; min-width:max-content">
            <div id="partialInfoMenu"></div>
        </div>
    </div>
</div>
<div id="myApptDeleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myDeleteApptModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="partialInfoDelete"></div>
        </div>
    </div>
</div>
<div id="myApptConfirmModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myConfirmApptModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="partialInfoConfirm"></div>
        </div>
    </div>
</div>
<div id="myApptInfoModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myInfoApptModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="partialInfoInformatii"></div>
        </div>
    </div>
</div>

<partial name="_LoadingSpinner"/>

@section Scripts{

    <script type="text/javascript" src="~/js/appointmentsIndex.js"></script>
    <script type="text/javascript" src="~/js/editAddApptPartial.js"></script>
    <script type="text/javascript" src="~/js/validationRulesAppt.js"></script>
    <script type="text/javascript">
        // Clear the existing appts.
        $('.appt-no-height').remove();

        // initial data load.
        window.setTimeout(function () {
            getAppointmentsForSelectedDate();
        },
            100);

        /* on load, scroll to a sensible hour */
        scrollToWorkingHours();
                                /*end page load*/
    </script>

}

DeltaQrCode/Views/Appointments/_AddAppointmentPartial.cshtml
@using DeltaQrCode.ModelsDto
@using Microsoft.AspNetCore.Razor.TagHelpers
@model DeltaQrCode.ViewModels.Appointments.AppointmentVM

<style>
    .modal-min-height {
        min-height: 450px;
    }

    .required-field::before {
        content: "*";
    }

    .margin150left {
        margin-left: 150px;
    }
</style>

<input id="defaultServiciu" hidden="hidden" data-value="@Model.Serviciu" />
<input id="defaultDurata" hidden="hidden" data-value="30" />
<div class="modal-header">
    <h3 id="myModalLabel">Adauga programare</h3>
    <button type="button" class="close float-right" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div>
    <form id="apptform" method="post">
        @Html.AntiForgeryToken()
        <div class="modal-body modal-min-height" id="apptModalBody">

            <div class="form-group">
                <input id="RampId" hidden="hidden" asp-for="RampId" />
            </div>
            <span id="availableHourSpan"> </span>

            <div class="form-group">
                <h6 style="margin-left:20px;">Data programare</h6>
                <div class="col-md-6">
                    <input id="datepickerModal" asp-for="DataAppointment" type="text" class="form-control changeable changeableDateTimeRamp" placeholder="Selecteaza data" />
                </div>
            </div>
            <div class="form-group form-inline">
                <label class="form-check-label col-md-3 required-field">Ora</label>
                <div class="col-md-9">
                    <div class="form-group">
                        @Html.DropDownListFor(model => model.StartTime_Hour, ViewData["hours"] as SelectList, new { @class = "form-control changeable changeableDateTimeRamp" })
                        @*<input id="StartTime_Hour" type="number" class="form-control changeable" asp-for="StartTime_Hour" />*@
                    </div>
                    <div class="form-group">
                        @Html.DropDownListFor(model => model.StartTime_Minutes, ViewData["minutes"] as SelectList, new { @class = "form-control changeable changeableDateTimeRamp" })
                        @*<input id="StartTime_Minutes" type="number" class="form-control changeable" asp-for="StartTime_Minutes" />*@
                    </div>

                    @Html.ValidationMessageFor(model => model.StartTime_Hour, "", new { @class = "text-danger" })
                    @Html.ValidationMessageFor(model => model.StartTime_Minutes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6 col-sm-4">
                    @Html.LabelFor(model => model.DurataInMinute, htmlAttributes: new { @class = "control-label col-md-3 required-field" })
                    <div class="col-md-9">
                        <input id="durataValue" class="changeable changeableDateTimeRamp" hidden="hidden" data-value="30" />
                        <input id="selectieBunaElem" hidden="hidden" value="false" />
                        <select class="form-control" id="Durata" asp-for="DurataInMinute" data-placeholder="@Model.DurataInMinute" value="@Model.DurataInMinute"></select>
                        @Html.ValidationMessageFor(model => model.DurataInMinute, "", new { @class = "text-danger error_span" })
                    </div>
                </div>

                <div class="form-group col-md-6 col-sm-4">
                    @Html.LabelFor(model => model.Serviciu, htmlAttributes: new { @class = "control-label col-md-3 required-field", @id = "serviciuLabel", @name = "serviciuLabel" })
                    <div class="col-md-9">
                        <select id="serviciu" class="changeable" asp-for="Serviciu" data-placeholder="@Model.Serviciu" value="@Model.Serviciu"></select>

                        @Html.ValidationMessageFor(model => model.Serviciu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.NumarInmatriculare, htmlAttributes: new { @class = "control-label col-md-3 required-field" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.NumarInmatriculare, new { htmlAttributes = new { @class = "form-control half-margin-bottom validate changeable" } })
                    @Html.ValidationMessageFor(model => model.NumarInmatriculare, "", new { @class = "text-danger error_span" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NumeClient, htmlAttributes: new { @class = "control-label col-md-3 required-field" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.NumeClient, new { htmlAttributes = new { @class = "form-control half-margin-bottom validate changeable" } })
                    @Html.ValidationMessageFor(model => model.NumeClient, "", new { @class = "text-danger error_span" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.NumarTelefon, htmlAttributes: new { @class = "control-label col-md-3 required-field" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.NumarTelefon, new { htmlAttributes = new { @class = "form-control half-margin-bottom validate changeable" } })
                    @Html.ValidationMessageFor(model => model.NumarTelefon, "", new { @class = "text-danger error_span" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.EmailClient, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.EmailClient, new { htmlAttributes = new { @class = "form-control half-margin-bottom validate changeable" } })
                    @Html.ValidationMessageFor(model => model.EmailClient, "", new { @class = "text-danger error_span" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Observatii, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.TextAreaFor(model => model.Observatii, 3, 40, new { htmlAttributes = new { @class = "form-control half-margin-bottom changeable" } })
                    @Html.ValidationMessageFor(model => model.Observatii, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

        <div>
            <p id="serverErrorMsg" style="color:red; padding: 5px;"></p>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Inchide</button>
            <button class="btn btn-outline-success btn-ok" id="apptsAddButton">Adauga</button>
        </div>
    </form>

</div>


<script type="text/javascript" src="~/js/select2AddEditAppt.js"></script>

DeltaQrCode/Views/Appointments/_ConfirmAppointmentPartial.cshtml
@using DeltaQrCode.ModelsDto
@using Microsoft.AspNetCore.Razor.TagHelpers
@model DeltaQrCode.ViewModels.Appointments.ConfirmVM





<div class="modal-header">

    <h3 id="myConfirmApptModalLabel"> Mesaj de confirmare  </h3>

</div>

<div class="modal-body">
    <input type="hidden" data-value="@Model.Confirm" id="confirmBool" />
    <h5>@(!Model.Confirm? "Esti sigur ca doresti sa anulezi confirmarea?" : "Esti sigur ca doresti sa confirmi aceasta programare?")</h5>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default btn-outline-dark " data-dismiss="modal">Inchide</button>
    <a class="btn btn-outline-primary btn-ok" id="actionConfirm" data-value="@Model.Id">@(!Model.Confirm?"Anuleaza confirmarea" : "Confirma")</a>
</div>


<script type="text/javascript">

    $("#actionConfirm").one("click",function () {
        $(this).attr("disabled", "disabled");

        var model = { id: $("#actionConfirm").attr("data-value"), confirm: $("#confirmBool").attr("data-value") };

        $.ajax({
            type: "POST",
            url: "@Url.Action("ConfirmAppt", "Appointments")",
            data: model,
            dataType:"json",
            success: function (response) {
                CloseModalById('myApptConfirmModal');
                ShowHeaderAlert(response, "success", 5000);
                clearAppointments();
                getAppointmentsForSelectedDate();
            },
            error: function (error) {
                CloseModalById('myApptConfirmModal');
                swalErrorTimer(error.responseText, 7000);

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("ErrorModal","Error")",
                    dataType: "json",
                    traditional: true,
                    contentType: 'application/json',
                    success: function (response) {
                        $("#GetModalCode").html(response);
                        $("#ErrorModal").modal('show');
                    },
                    error: function (error) {
                        alert(error);
                    }
                });
            }
        });
    });

</script>

DeltaQrCode/Views/Appointments/_DeleteAppointmentPartial.cshtml
@using DeltaQrCode.ModelsDto
@using Microsoft.AspNetCore.Razor.TagHelpers
@model int




<div class="modal-header">

    <h3 id="myDeleteApptModalLabel"> Mesaj de confirmare  </h3>

</div>

<div class="modal-body">
    <h5> Esti sigur ca doresti sa stergi aceasta programare?</h5>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default btn-outline-dark " data-dismiss="modal">Inchide</button>
    <a class="btn btn-outline-danger btn-ok" id="confirmDelete" data-value="@Model">Sterge</a>
</div>


<script type="text/javascript">

    $("#confirmDelete").one("click",function () {
        $(this).attr("disabled", "disabled");

        var model = { id: $("#confirmDelete").attr("data-value") };

        $.ajax({
            type: "POST",
            url: "@Url.Action("ConfirmDelete", "Appointments")",
            data: model,
            dataType:"json",
            success: function (response) {
                CloseModalById('myApptDeleteModal');
                ShowHeaderAlert(response, "success", 5000);
                clearAppointments();
                getAppointmentsForSelectedDate();
            },
            error: function (error) {
                CloseModalById('myApptDeleteModal');
                swalErrorTimer(error.responseText, 7000);

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("ErrorModal","Error")",
                    dataType: "json",
                    traditional: true,
                    contentType: 'application/json',
                    success: function (response) {
                        $("#GetModalCode").html(response);
                        $("#ErrorModal").modal('show');
                    },
                    error: function (error) {
                        alert(error);
                    }
                });
            }
        });
    });

</script>

DeltaQrCode/Views/Appointments/_MenuAppointmentPartial.cshtml
@using DeltaQrCode.ModelsDto
@using Microsoft.AspNetCore.Razor.TagHelpers
@using System.Security.Claims
@model DeltaQrCode.ViewModels.Appointments.ConfirmVM

<div class="modal-body">
    <div class="row">

        <div class="col-md-3">
            <div class="btn btn-squared-default-plain btn-secondary" id="infoButton" type="button" data-value="@Model.Id"><br /><i class="fas fa-info-circle fa-4x"></i> <br />  Informatii </div>
        </div>

        <div class="col-md-3">
            <div class="btn btn-squared-default-plain btn-primary" id="confirmButton" type="button" data-value="@Model.Id" data-confirm="@Model.Confirm">
                @if (Model.Confirm)
                {
                    <br /><i class="fas fa-check-circle fa-4x"></i> <br />
                }
                else
                {
                    <br /><i class="fas fa-times-circle fa-4x"></i> <br />
                }

                @(!Model.Confirm ? "Anuleaza programarea" : "Confirma")
            </div>
        </div>

        <div class="col-md-3">
            <div class="btn btn-squared-default-plain btn-warning text-white" id="editButton" type="button" data-value="@Model.Id"><br /><i class="fas fa-pen-square fa-4x "></i> <br />Editeaza</div>
        </div>
        @if (User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value == "admin")
        {
            <div class="col-md-3">
                <div class="btn btn-squared-default-plain btn-danger" id="deleteButton" type="button" data-value="@Model.Id"><br /><i class="fas fa-trash-alt fa-4x"></i> <br />  Sterge </div>
            </div>
        }

    </div>

</div>

DeltaQrCode/Views/Appointments/_RampPartial.cshtml
@model int

<div id="Ramp@(Model)" class="col-lg-6 col-md-8 col-sm-12">
    <div> Rampa @(Model)</div>
    <div class="date-control-container">

        <div class="hour-container ramp" value="@Model" data-value="@Model">
            @for (int i = 8; i < 18; i++)
            {
                <div class="hour@(i)_00 hour">
                    <div class="hourText">@i:00</div>
                </div>
                string breaktime = i == 12 ? "hour-red" : "";
                <div class="hour@(i)_30 hour @breaktime">
                    <div class="hourText">@i:30</div>
                </div>
            }
            <div class="hour18_00 hour">
                <div class="hourText">18:00</div>
            </div>
            <div style="height: auto; width: auto; background-color: lightgray;"></div>
        </div>
    </div>
</div>