DeltaQrCode/ViewModels/Scheduler/AppointmentModalVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeltaQrCode.ViewModels.Scheduler
{
    using AppointmentsDb.ModelsDto;

    using DeltaQrCode.ModelsDto;
    using DeltaQrCode.Services;

    using Microsoft.AspNetCore.Mvc.Rendering;

    public class AppointmentModalVm
    {

        public DateTime ActiveDate { get; set; }

        public ActionType CreateOrEdit { get; set; }

        public AppointmentForProUiDto Appointment { get; set; }

        public AppointmentModalVm()
        {
            Appointment = new AppointmentForProUiDto();
        }
        public AppointmentModalVm(ActionType createOrEdit)
        {
            Appointment = new AppointmentForProUiDto();
            CreateOrEdit = createOrEdit;
        }
        public AppointmentModalVm(string userId, AppointmentForProUiDto appointment, ActionType? creteOrEdit = null)
        {
            Appointment = appointment;
            CreateOrEdit = ActionType.Add;
        }
    }
}

DeltaQrCode/ViewModels/Scheduler/AppointmentsIndexVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeltaQrCode.ViewModels.Scheduler
{
    using DeltaQrCode.ModelsDto;

    public class AppointmentsIndexVm
    {
        public AppointmentsIndexVm(int rampId, List<AppointmentForProUiDto> appointments)
        {
            RampId = rampId;
            Appointments = appointments;
        }
        public int RampId { get; set; }
        public List<AppointmentForProUiDto> Appointments { get; set; }
    }
}

DeltaQrCode/ViewModels/Scheduler/CalendarVm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeltaQrCode.ViewModels.Scheduler
{
    using AppointmentsDb.ModelsDto.Custom;

    using DeltaQrCode.Services;

    using Microsoft.AspNetCore.Mvc.Rendering;

    public class CalendarVm
    {
        /// <summary>
        /// The list of ProfessionalsAccessableEmployees in a format MVC can use for selection.
        /// </summary>
        public List<DateTime> AvailableDates { get; set; }

        public DateTime ActiveDate { get; set; }

        public Guid CurrentProfessionalId { get; set; }

        public CalendarVm(string userId)
        {

        }

    }


}

DeltaQrCode/ViewModels/Scheduler/StatusVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeltaQrCode.ViewModels.Scheduler
{
    public class StatusVM
    {
        public StatusVM()
        {

        }

        public StatusVM(bool isSuccess, string successMessage, string failMessage)
        {
            IsSuccess = isSuccess;
            SuccessMessage = successMessage;
            FailMessage = failMessage;
        }

        public bool IsSuccess { get; set; }
        public string SuccessMessage { get; set; }
        public string FailMessage { get; set; }
    }
}

DeltaQrCode/ViewModels/Scheduler/ValidationMsg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeltaQrCode.ViewModels.Scheduler
{
    public class ValidationMsg
    {
        public string ValidationMessage { get; set; }
    }
}

DeltaQrCode/Controllers/SchedulerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace DeltaQrCode.Controllers
{
    using System.Net;
    using System.Text;


    using DeltaQrCode.ModelsDto;
    using DeltaQrCode.ViewModels.Scheduler;

    using Microsoft.AspNetCore.Authorization;

    using Newtonsoft.Json;

    [Authorize]
    public class SchedulerController : Controller
    {
        // GET: Appointments
        public ActionResult Index(string startDateString, string activeDateString, string professionalIdString)
        {


            // Get the appointments with a list of employees details this user can access
            CalendarVm calendarVm = new CalendarVm(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value);
            var startDate = GetStartDateFromStringParam(startDateString);
            var activeDate = GetStartDateFromStringParam(activeDateString);

            if (startDate < DateTime.Now) startDate = DateTime.Now;
            if (activeDate < startDate) activeDate = startDate;

            if (activeDate.Date > startDate.Date.AddDays(3))
            {
                startDate = activeDate.AddDays(-2);
            }

            calendarVm.AvailableDates = CreateAvailableDatesList(startDate);
            calendarVm.ActiveDate = activeDate;

            return View(calendarVm);
        }



        public JsonResult GetAppointmentsForDate(string apptDate)
        {
            DateTime dt;
            DateTime.TryParse(apptDate, out dt);
            if (dt == new DateTime())
                dt = DateTime.Now.Date;

            //List<AppointmentForProUiDto> appointmentsList = _appointmentQueries.GetUiDto_AppointmentsForProfessionalOrEmployee(User.Identity.GetUserId(), professionalId, dt.Date, dt.Date.AddDays(1));
            List<AppointmentForProUiDto> appointmentsList = AppointmentForProUiDto.FakeList(dt);
            var rampIds = appointmentsList.Select(x => x.RampId).Distinct();
            var result = new List<AppointmentsIndexVm>();
            foreach (var item in rampIds)
            {
                var list = appointmentsList.Where(x => x.RampId == item).ToList();
                var aux = new AppointmentsIndexVm(item, list);
                result.Add(aux);
            }

            return new JsonResult(result);
            //return Json(/*appointmentsList*/"");
        }


        public ActionResult EditModalNew(string startDateStr, string startHour, string rampNr)
        {
            DateTime startDate = DateTime.Parse(startDateStr);
            var s = startHour.Split('_');
            DateTime appointmentStart = startDate.AddHours(int.Parse(s[0])).AddMinutes(int.Parse(s[1]));

            var appointment = new AppointmentForProUiDto(appointmentStart);
            appointment.DurationInMinutes = 60;
            appointment.NrMasina = "";
            appointment.NumeClient = "";
            appointment.PhoneNumber = "";

            AppointmentModalVm appointmentVm = new AppointmentModalVm(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value, appointment, ActionType.Add);

            return PartialView("_EditAppointmentPartial", appointmentVm);
        }


        public ActionResult EditModal(Guid? id, string startDateStr)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }

            // Get the appointment for the professional.
            //AppointmentForProUiDto appointment = _appointmentQueries.GetUiDto_AppointmentByIdForProfessionalOrEmployee(User.Identity.GetUserId(), professionalId, (Guid)id);

            //if (appointment == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            //AppointmentModalVm appointmentVm = new AppointmentModalVm(User.Claims.FirstOrDefault(x => x.Type == "id")?.Value, professionalId, appointment);
            DateTime startDate = DateTime.Parse(startDateStr);
            var appointment = new AppointmentModalVm
            {
                Appointment = AppointmentForProUiDto.FakeList(startDate).FirstOrDefault(x => x.AppointmentId == id),
                CreateOrEdit = ActionType.Edit,
                ActiveDate = startDate
            };
            return PartialView("_EditAppointmentPartial", appointment /*,appointmentVm*/);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditModal([Bind(include: "ProfessionalId, AppointmentId,AppointmentIndex,AppointmentType,NrMasina,NumeClient,EmailAddress,PhoneNumber,TelephoneMobile,DurationInMinutes,IsCancelled,ProfessionalNotes,StartTime_Date,StartTime_Hour,StartTime_Minutes")] AppointmentForProUiDto appointment)
        {
            if (ModelState.IsValid)
            {
                //_appointmentQueries.AddOrUpdateAppointmentFromDto(User.Identity.GetUserId(), appointment.ProfessionalId.ToString(), appointment);

                return Content("success");
            }
            else
            {
                // List the errors.
                StringBuilder sbError = new StringBuilder();
                foreach (var row in ModelState.Values)
                {
                    foreach (var err in row.Errors)
                    {
                        sbError.AppendLine(err.ErrorMessage);
                    }
                }
                return Content(sbError.ToString());
            }

        }



        #region "Helpers"

        DateTime GetStartDateFromStringParam(string dateString)
        {
            if (String.IsNullOrWhiteSpace(dateString))
            {
                dateString = DateTime.Now.Date.ToString();
            }

            DateTime dt;
            if (DateTime.TryParse(dateString, out dt))
            {
                return dt;
            }

            return DateTime.Now;

        }

        /// <summary>
        /// Return a list of dates
        /// </summary>
        /// <param name="startDate"></param>
        /// <returns></returns>
        List<DateTime> CreateAvailableDatesList(DateTime startDate)
        {
            var numberOfDaysToShow = 31;
            List<DateTime> availableDatesList = new List<DateTime>();
            for (int i = 0; i < numberOfDaysToShow; i++)
            {
                availableDatesList.Add(startDate.Date.AddDays(i));
            }

            return availableDatesList;
        }

        #endregion


    }
}

DeltaQrCode/Views/Scheduler/Index.cshtml
@using System.Security.Cryptography.X509Certificates
@model DeltaQrCode.ViewModels.Scheduler.CalendarVm

@{
    ViewBag.Title = "Calendar";
}
<head>
    <link href="~/css/SchedulerIndexStyle.css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdn.rawgit.com/asvd/dragscroll/master/dragscroll.js"></script>
</head>

<div class="container">
    <div class="form-row">
        <div class="form-group col-md-4">
            <label class="col-form-label"></label>
            <input id="datepicker" class="form-control" placeholder="Selecteaza data" />
            <span class="text-danger"></span>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        @for (int rampNr = 1; rampNr < 5; rampNr++)
        {
            <partial model="@rampNr" name="_RampPartial" />
        }
    </div>
</div>
<!--  this is the modal dialog that will house the partial content-->
<div id="myApptModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="partialInfo"></div>
        </div>
    </div>
</div>


@section Scripts{

    <script type="text/javascript">


        $(function() {
            var dateToday = new Date();
            $("#datepicker").datepicker({ dateFormat: "yy-mm-dd" }).datepicker({ minDate:0 }).datepicker("setDate", dateToday);
        });
        $(function() {

        });

        $(function() {
            // Clear the existing appts.
            $('.appt-no-height').remove();

            var scrollToWorkingHours = function() {
                $('.hour-container').animate({ scrollTop: '125px' }, 'slow');
            };

            /* Enables scrolling to a set position  scrollToId('.hour-container', '#hour4');*/
            var scrollToId = function(scrollContainer, aid) {
                var aTag = $(aid);
                $(scrollContainer).animate({ scrollTop: aTag.offset().top }, 'slow');
            };

            var clearAppointments = function() {
                // Clear the existing appts.
                $('.appt-no-height').remove();
            };

            var apptNewModalDialog = function(startDate, startHour, rampNr) {
                var url = "/Scheduler/EditModalNew"; // the url to the controller
                $.get(url + '?startDateStr=' + startDate + '&startHour=' + startHour + '&rampNr=' + rampNr,
                    function(data) {
                        $('#partialInfo').html(data);
                        $('#myApptModal').modal('show');

                        var dateFromPage = $("#datepicker").val();
                        var datePage = new Date(dateFromPage);
                        $("#datepickerModal").datepicker({format:"yy-mm-dd"}).datepicker({ minDate: datePage }).datepicker("setDate", datePage);
                    });
            };

            var apptEditModalDialog = function(id, startHour) { // TODO: REMOVE startHour param after link with db. Now it is used for fakeList creation

                var url = "/Scheduler/EditModal"; // the url to the controller
                $.get(url + '?id=' + id + '&startDateStr=' + startHour  ,
                    function(data) {
                        $('#partialInfo').html(data);
                        $('#myApptModal').modal('show');

                        var dateFromPage = $("#datepicker").val();
                        var datePage = new Date(dateFromPage);
                        $("#datepickerModal").datepicker({format:"yy-mm-dd"}).datepicker({ minDate: datePage }).datepicker("setDate", datePage);

                    });
            };

            var showAppointmentsForDate = function(calendarDate) {


                $.get('@Url.Action("GetAppointmentsForDate", "Scheduler")',
                    { apptDate: calendarDate },
                    function(response) {

                        clearAppointments();

                        // Settings
                        var marginLeftPerItem = 20;
                        var oneHourPxHeight = 60;

                        var oneMinutePxHeight = oneHourPxHeight / 60;
                        if (response != "") {

                            //var obj = $.parseJSON(response);
                            $.each(response,
                                function(key, data) {
                                    var rampId = "#Ramp" + data.rampId;
                                    // Add appts in the right position
                                    for (var i = 0; i < data.appointments.length; i++) {
                                        var row = data.appointments[i];
                                        var minutesText = row.startTime_Minutes === 0 ? '00' : row.startTime_Minutes;
                                        var apptRow = $(rampId + " " + ".hour" + row.startTime_Hour + "_"+ minutesText);


                                        var stringToAppend = '<div id="appt' +
                                            row.appointmentId +
                                            '" class="appt-no-height">' +
                                            row.nrMasina +
                                            ' | ' +
                                            row.numeClient +
                                            ' | ' +
                                            row.phoneNumber +
                                            ' | ' +
                                            row.appointmentTypeAsDisplay +
                                            ' </div>';

                                        apptRow.append(stringToAppend);

                                        var objHeight = (row.durationInMinutes * oneMinutePxHeight) + 'px';
                                        var marginTop = (row.startTime_Minutes * oneMinutePxHeight) + 'px';
                                        var marginLeft = ((apptRow.children().length - 1) * marginLeftPerItem) + 'px';

                                        var thisAppt = $("#appt" + row.appointmentId);
                                        thisAppt.css("height", objHeight);
                                        thisAppt.css("margin-top", marginTop);
                                        thisAppt.css("margin-left", marginLeft);

                                        //default color is silver on appt-no-height.
                                        switch (row.appointmentType) {
                                        case 2:
                                            thisAppt.css("background-color", 'lightblue');
                                            break;
                                        case 1024:
                                            thisAppt.css("background-color", 'lightgreen');
                                            break;
                                        default:
                                            // do nothing.
                                            break;
                                        }
                                    }
                                });
                        };

                        /* click event for editing an appt*/
                        $('.appt-no-height').on('click',
                            function(event) {
                                // dont allow the event to propagate to hour click.
                                event.stopPropagation();

                                var fullId = this.id.replace('appt', '');
                                var selectedDateDiv = $('#datepicker');
                                apptEditModalDialog(fullId, selectedDateDiv.val()); 
                            });

                        /* scroll to a better position */
                        scrollToWorkingHours();
                    });
            };



            /* click event on the hour */
            $('.hour').on('dblclick',
                function (elm) {

                    var startHourOnly = $(this).attr("class").replace('hour-red', '');
                    startHourOnly  = startHourOnly.replaceAll("hour", "");

                    var selectedDateDiv = $('#datepicker');
                    var rampNr = $(this).closest(".ramp").val();
                    // Make the modal here!
                    apptNewModalDialog(selectedDateDiv.val(), startHourOnly,rampNr);
                });


            /* Get the appointments for whatever date is selected */
            var getAppointmentsForSelectedDate = function() {
                var selectedDateDiv = $('#datepicker');
                var parts = selectedDateDiv.val();
                showAppointmentsForDate(parts);
            }


            // initial data load.
            window.setTimeout(function() {
                    getAppointmentsForSelectedDate();
                },
                1000);




            /* Dates ensure clicked, not dragged! */
            var $dateControl = $('.date');
            $dateControl.on('mousedown',
                function(evt) {
                    $dateControl.on('mouseup mousemove',
                        function handler(evt) {
                            if (evt.type === 'mouseup') {
                                // click
                                $('.date').removeClass('date-selected');

                                $(evt.currentTarget).addClass('date-selected');
                                showAppointmentsForDate(evt.currentTarget.innerHTML);
                            } else {
                                // drag
                            }
                            $dateControl.off('mouseup mousemove', handler);
                        });
                });


            /* on load, scroll to a sensible hour */
            scrollToWorkingHours();

            $("#datepicker").on("change",
                function () {
                    clearAppointments();
                    getAppointmentsForSelectedDate();
                });
            /*end page load*/
        });
    </script>

}