DeltaQrCode/ViewModels/HotelAnvelope/HotelListViewModel.cs
using System.Collections.Generic;

namespace DeltaQrCode.ViewModels
{
    using DeltaQrCode.ViewModels.HotelAnvelope;

    public class HotelListViewModel
    {

        public HotelListViewModel()
        {

        }

        public HotelListViewModel(PaginatedList<HotelAnvelopaVm> paginatedModel)
        {
            List = paginatedModel;
        }

        public HotelListViewModel(PaginatedList<AnvelopaVM> paginatedResult)
        {
            anvList = paginatedResult;
        }
        public HotelListViewModel(List<HotelAnvelopaVm> list, int pageIndex, int pageSize)
        {
            List = PaginatedList<HotelAnvelopaVm>.Create(list, pageIndex, pageSize);
        }

        public PaginatedList<HotelAnvelopaVm> List { get; set; }

        public HotelListViewModel(List<AnvelopaVM> list, int pageIndex, int pageSize)
        {
            anvList = PaginatedList<AnvelopaVM>.Create(list, pageIndex, pageSize);
        }

        public PaginatedList<AnvelopaVM> anvList { get; set; }
    }
}

DeltaQrCode/ViewModels/HotelListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeltaQrCode.ViewModels
{
    public class HotelListViewModel
    {
        public HotelListViewModel()
        {

        }
        public HotelListViewModel(List<HotelViewModel> list, int totalPagesNR, int currentPage)
        {
            List = list;
            TotalPages = totalPagesNR;
            CurrentPage = currentPage;
        }

        public List<HotelViewModel> List { get; set; }
        public int TotalPages { get; set; }
        public int CurrentPage { get; set; }

    }
}

DeltaQrCode/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DeltaQrCode.ViewModels;

namespace DeltaQrCode.Controllers
{
    using DeltaQrCode.ModelsDto;

    using AutoMapper;

    using DeltaQrCode.HelpersAndExtensions;
    using DeltaQrCode.Services.Hotel;
    using DeltaQrCode.ViewModels.HotelAnvelope;

    using Microsoft.AspNetCore.Authorization;

    using Newtonsoft.Json;
    using Serilog;
    using ClosedXML.Excel;
    using System.IO;
    using DeltaQrCode.Services.Hotel_Positions;

    [Authorize]
    public class HotelController : Controller
    {
        private readonly IHotelService _hotelService;
        private readonly IHotelPositionsService _hotelPositionsService;
        private readonly IMapper _mapper;
        private const int PageSize = 20;


        public HotelController(IHotelService hotelService, IHotelPositionsService hotelPositionsService, IMapper mapper)
        {
            _hotelService = hotelService;
            _hotelPositionsService = hotelPositionsService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> EditSetAnv(uint id, string actionType)
        {

            try
            {
                var set = await _hotelService.GetSetAnvelopeByIdAsync(id);
                var setvm = _mapper.Map<SetAnvelopeVM>(set.Entity);

                var anvList = await _hotelService.SearchAnvelopeByStatusCurentAsync("InRaft", id, 1, PageSize);
                var anvListvm = _mapper.Map<List<AnvelopaVM>>(anvList.Entity);
                foreach (var item in anvListvm)
                {
                    item.OldUzura = item.Uzura;
                    item.OldPozitieId = item.PozitieId;
                }

                var masina = await _hotelService.GetMasinaForSetIdAsync(set.Entity.Id);
                var masinavm = _mapper.Map<MasinaVM>(masina.Entity);

                var client = await _hotelService.GetClientForSetIdAsync(set.Entity.Id);
                var clientvm = _mapper.Map<ClientHotelVM>(client.Entity);

                var setAnv = new AddEditSetAnvelopeVM();

                setAnv.Client = clientvm;
                setAnv.Masina = masinavm;
                setAnv.SetAnvelope = setvm;
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaFata") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaFata") : new AnvelopaVM("StangaFata"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaFata") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaFata") : new AnvelopaVM("DreaptaFata"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaSpate") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaSpate") : new AnvelopaVM("StangaSpate"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaSpate") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaSpate") : new AnvelopaVM("DreaptaSpate"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional1") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional1") : new AnvelopaVM("Optional1"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional2") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional2") : new AnvelopaVM("Optional2"));

                return View(setAnv);
            }
            catch (Exception e)
            {

                Log.Error(e, "Ceva nu a mers bine la modificarea setului de anvelope [GET] in controller!");
                return BadRequest("Ceva nu a mers bine la modificarea setului de anvelope [GET] in controller!");
            }



        }

        public async Task<IActionResult> SearchAnvelopeByStatusCurent(string searchString, uint setId, int pageNumber = 1)
        {
            var anvelopeResult = await _hotelService.SearchAnvelopeByStatusCurentAsync(searchString, setId, pageNumber, PageSize);
            var anvelope = anvelopeResult.Entity;

            var result = _mapper.Map<List<AnvelopaVM>>(anvelope);

            var paginatedModel = PaginatedList<AnvelopaVM>.Create(result, pageNumber, 3);
            var model = new HotelListViewModel(paginatedModel);
            return PartialView("_EditSetAnvelopeListPartial", model);
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> Search(string searchString, int pageNumber = 1)
        {
            //var anvelopeResult = await _hotelService.SearchAnvelopeAsync(searchString, pageNumber, PageSize);
            //var anvelope = anvelopeResult.Entity;

            var sets = await _hotelService.SearchSetAnvelopeAsync(searchString, pageNumber, PageSize);
            var setsAnv = sets.Entity;

            //var mapper = _mapper.Map<List<HotelAnvelopaVm>>(anvelope);

            var mapper = new List<HotelAnvelopaVm>();
            //var listanvVm = _mapper.Map<List<SetAnvelopeVM>>(setsAnv);
            foreach (var item in setsAnv)
            {

                var client = await _hotelService.GetClientByIdAsync(item.ClientId);
                var masina = await _hotelService.GetMasinaByIdAsync(item.MasinaId);


                var anv = _mapper.Map<HotelAnvelopaVm>(item);
                anv.Client = _mapper.Map<ClientHotelVM>(client.Entity);
                anv.Masina = _mapper.Map<MasinaVM>(masina.Entity);

                mapper.Add(anv);
            }

            var paginatedModel = PaginatedList<HotelAnvelopaVm>.Create(mapper, pageNumber, PageSize);
            var model = new HotelListViewModel(paginatedModel);
            return PartialView("_HotelList", model);
        }



        public async Task<IActionResult> SearchAnvSetByAnvStatus(string searchString,string status, int pageNumber = 1)
        {

            var sets = await _hotelService.SearchSetAnvelopeByStatusAsync(searchString,status, pageNumber, PageSize);
            var setsAnv = sets.Entity;


            var mapper = new List<HotelAnvelopaVm>();
            foreach (var item in setsAnv)
            {

                var client = await _hotelService.GetClientByIdAsync(item.ClientId);
                var masina = await _hotelService.GetMasinaByIdAsync(item.MasinaId);


                var anv = _mapper.Map<HotelAnvelopaVm>(item);
                anv.Client = _mapper.Map<ClientHotelVM>(client.Entity);
                anv.Masina = _mapper.Map<MasinaVM>(masina.Entity);

                mapper.Add(anv);
            }

            var paginatedModel = PaginatedList<HotelAnvelopaVm>.Create(mapper, pageNumber, PageSize);
            var model = new HotelListViewModel(paginatedModel);
            return PartialView("_HotelList", model);
        }

        public async Task<IActionResult> SearchAnvelopeForInfoSet(string searchString, uint setId, int pageNumber = 1)
        {
            var anvelopeResult = await _hotelService.SearchAnvelopeByStatusCurentAsync(searchString, setId, pageNumber, PageSize);
            var anvelope = anvelopeResult.Entity;

            var result = _mapper.Map<List<AnvelopaVM>>(anvelope);

            var paginatedModel = PaginatedList<AnvelopaVM>.Create(result, pageNumber, 3);
            var model = new HotelListViewModel(paginatedModel);
            return PartialView("_InfoAnvelopeList", model);
        }


        [HttpGet]
        public async Task<IActionResult> InfoModal(uint id, string actionType)
        {
            try
            {
                ActionType actType = ActionType.Info;

                var set = await _hotelService.GetSetAnvelopeByIdAsync(id);
                var setvm = _mapper.Map<SetAnvelopeVM>(set.Entity);

                var anvList = await _hotelService.GetAnvelopeBySetIdAsync(id);
                var anvListvm = _mapper.Map<List<AnvelopaVM>>(anvList.Entity);
                foreach (var item in anvListvm)
                {
                    item.OldPozitieId = item.PozitieId;
                }

                var masina = await _hotelService.GetMasinaForSetIdAsync(set.Entity.Id);
                var masinavm = _mapper.Map<MasinaVM>(masina.Entity);

                var client = await _hotelService.GetClientForSetIdAsync(set.Entity.Id);
                var clientvm = _mapper.Map<ClientHotelVM>(client.Entity);

                var setAnv = new AddEditSetAnvelopeVM();

                setAnv.Client = clientvm;
                setAnv.Masina = masinavm;
                setAnv.SetAnvelope = setvm;
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaFata") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaFata") : new AnvelopaVM("StangaFata"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaFata") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaFata") : new AnvelopaVM("DreaptaFata"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaSpate") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "StangaSpate") : new AnvelopaVM("StangaSpate"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaSpate") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "DreaptaSpate") : new AnvelopaVM("DreaptaSpate"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional1") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional1") : new AnvelopaVM("Optional1"));
                setAnv.Anvelope.Add(anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional2") != null ? anvListvm.FirstOrDefault(x => x.PozitiePeMasina == "Optional2") : new AnvelopaVM("Optional2"));

DeltaQrCode/Views/Hotel/Index.cshtml
@{
    ViewBag.Title = "HotelAnvelope";
}
<head>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link href="~/css/SchedulerIndexStyle.css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdn.rawgit.com/asvd/dragscroll/master/dragscroll.js"></script>
</head>


<div id="HeaderAlert" class="alert" role="alert">
</div>
<input type="text" id="hotelListState" value="0" hidden="hidden" />
<div class="filicontainer text-center">
    <div class="input-group rounded">
        <input type="text" id="search" class="form-control rounded" placeholder="Search" aria-label="Search"
               aria-describedby="search-addon" />
        <span class=" button input-group-text border-secondary btn-outline-secondary" id="search-addon">
            <i class="fas fa-search"></i>
        </span>
        <div style="margin-left:20px;"> <select style="min-width:120px;" class="form-control" id="selectStatus"></select> </div>
        <div style="margin-left:30px;" type="button" id="AddSetAnv" class="btn btn-success">Adauga Set Anvelope</div>
        <a style="margin-left:10px;" type="button" id="DownloadExcel" asp-action="download" asp-controller="Hotel" class="btn btn-secondary"><i class="fas fa-file-download"></i></a>
    </div>
    <br />
</div>
<div id="tableResult" class="filicontainer">

</div>


<div id="myHotelModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div id="partialInfo"></div>
        </div>
    </div>
</div>

<div id="myHotelDeleteModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div id="partialInfoDelete"></div>
        </div>
    </div>
</div>


<div id="GetModalCode"></div>

<partial name="_LoadingSpinner" />



@section Scripts{
    <script type="text/javascript" src="~/js/addSetAnvPartial.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            var data = { searchString: $("#search").val(), page: 1 };
            $("#tableResult").load("/Hotel/Search",
                data,
                function () {
                    setPagination();
                });
        });
        $("#search-addon").on("click",
            function (event) {
                event.preventDefault();
                var data = { searchString: $("#search").val(), page: 1 };
                $("#tableResult").load("/Hotel/Search",
                    data,
                    function () {
                        setPagination();
                    });
            });

        $("#selectStatus").on("change",
            function (event) {
                event.preventDefault();
                var statusValue = $("#selectStatus").val();
                if (statusValue != "Toate") {
                    var data = { searchString: $("#search").val(), status: statusValue, page: 1 };
                    $("#tableResult").load("/Hotel/SearchAnvSetByAnvStatus",
                        data,
                        function () {
                            setPagination();
                        });
                } else {
                    var data = { searchString: $("#search").val(), page: 1 };
                    $("#tableResult").load("/Hotel/Search",
                        data,
                        function () {
                            setPagination();
                        });
                }

            });

        $(document).on("click",
            ".customPagination",
            function (event) {
                event.preventDefault();
                var page = $(this).attr("data-pageNumber");
                var data = { searchString: $("#search").val(), pageNumber: page };
                $("#tableResult").load("/Hotel/Search",
                    data,
                    function () {
                        setPagination();
                    });
            });

        var setAnvNewAddModalDialog = function () {
            var url = "/Hotel/AddModalNew"; // the url to the controller
            $.get(url,
                function (data) {
                    $('#partialInfo').html(data);
                    $('#myHotelModal').modal('show');
                    var pos = $(".pozitieinraft");
                    pos.removeAttr("disabled");
                    pos.removeClass("disabled");
                    var statusVal = $(".statuscurent").val();
                    if (statusVal != "InRaft") {
                        pos.attr("disabled", "disabled");
                        pos.addClass("disabled");
                    }
                });
        };

        $("#selectStatus").select2({
            theme: "bootstrap4",
            allowClear: true,
            placeholder: "Status",
            ajax: {
                url: '/Hotel/GetStatusAnvelopeForIndex',
                contentType: "application/json; charset=utf-8",
                data: function (params) {
                    var query = {
                        term: params.term
                    }
                    return query;
                },
                processResults: function (result) {
                    return {
                        results: $.map(result,
                            function (item) {
                                return {
                                    id: item,
                                    text: item
                                };
                            }),
                    };
                }
            }
        });



        var deleteSetAnvModalDialog = function (id) {

            var url = "/Hotel/DeleteModal"; // the url to the controller
            $.get(url + '?id=' + id,
                function (data) {
                    $('#partialInfoDelete').html(data);
                    $('#myHotelDeleteModal').modal('show');
                    $('#confirmDelete').attr("data-deleteType", "set")
                });
        };

        $('#AddSetAnv').on('click',
            function (event) {
                // dont allow the event to propagate
                event.stopPropagation();
                setAnvNewAddModalDialog();
            });

        var setAnvInfoModalDialog = function (id, actionType) {

            var url = "/Hotel/InfoModal"; // the url to the controller
            $.get(url + '?id=' + id + '&actionType=' + "info",
                function (data) {
                    $('#partialInfo').html(data);
                    $('#myHotelModal').modal('show');

                    var statuses = $(".statuscurent");
                    $.each(statuses, function (index, item) {
                        enableOrDisablePositionForStatus(item);
                    })
                });
        };


        $(document).on('click',
            '.infoButton',
            function (event) {
                // dont allow the event to propagate
                event.stopPropagation();
                //console.log('aici');
                var id = $(this).attr("data-value");
                var actionType = $(this).attr("data-actionType");

                setAnvInfoModalDialog(id, actionType);
            });

        $(document).on('click',
            '.deleteButton',
            function (event) {
                // dont allow the event to propagate
                event.stopPropagation();
                var id = $(this).attr("data-value");
                deleteSetAnvModalDialog(id);
            });

        $(document).on("change",
            "#hotelListState",
            function (event) {
                event.preventDefault();
                var data = { searchString: $("#search").val(), page: 1 };
                $("#tableResult").load("/Hotel/Search", data, function () {
                    setPagination();
                });
            });

        var setPagination = function () {
            var hasPrev = $("#hasPrev").attr("data-value");
            var hasNext = $("#hasNext").attr("data-value");

            if (hasPrev == "true") {
                enablePrevious();
            } else if (hasPrev == "false") {
                disablePrevious();
            }

            if (hasNext == "true") {
                enableNext();
            } else if (hasNext == "false") {
                disableNext();
            }
        };

        var enablePrevious = function () {
            $(document).find("#buttonPrev").removeAttr("disabled");
            //$(document).find("#buttonPrev").removeClass("disabled");
            //console.log("Enable Previons");
        };
        var disablePrevious = function () {
            $(document).find("#buttonPrev").attr("disabled", "disabled");
            //$(document).find("#buttonPrev").addClass("disabled");
            //console.log("Disable Previons");

        };
        var enableNext = function () {
            $(document).find("#buttonNext").removeAttr("disabled");
            //$(document).find("#buttonNext").removeClass("disabled");
            /*  //*///console.log("Enable Next");

        };
        var disableNext = function () {
            $(document).find("#buttonNext").attr("disabled", "disabled");
            //$(document).find("#buttonNext").addClass("disabled");
            //console.log("Disable Next");

        };




    </script>


}

DeltaQrCode/Views/Hotel/_DeleteSetAnvPartial.cshtml
@using DeltaQrCode.ModelsDto
@using Microsoft.AspNetCore.Razor.TagHelpers
@model uint




<div class="modal-header">

    <h3 id="myDeleteModalLabel"> Mesaj de confirmare  </h3>

</div>

<div class="modal-body">
    <h5> Esti sigur ca doresti sa stergi acest reper? In urma operatiunii, nu mai poti vedea setul de anvelope in tabel.</h5>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default btn-outline-dark " data-dismiss="modal">Inchide</button>
    <a class="btn btn-outline-danger btn-ok" id="confirmDelete" data-value="@Model" data-deleteType="">Sterge</a>
</div>


<script type="text/javascript">

    $("#confirmDelete").one("click",function () {
                $(this).attr("disabled", "disabled");

        var model = { id: $("#confirmDelete").attr("data-value") };
        var url = "@Url.Action("ConfirmDeleteSet", "Hotel")";
        if ($(this).attr("data-deleteType") == "anv") {
            url = "@Url.Action("ConfirmDeleteAnvelopa", "Hotel")";
        }
        $.ajax({
            type: "POST",
            url: url,
            data: model,
            dataType:"json",
            success: function (response) {
                CloseModalById('myHotelDeleteModal');
                ShowHeaderAlert(response, "success", 5000);
                $('#hotelListState').change();
            },
            error: function (error) {
                CloseModalById('myHotelDeleteModal');
                swalErrorTimer(error.responseText, 7000);

                $.ajax({
                    type: "POST",
                    url: "@Url.Action("ErrorModal","Error")",
                    dataType: "json",
                    traditional: true,
                    contentType: 'application/json',
                    success: function (response) {
                        $("#GetModalCode").html(response);
                        $("#ErrorModal").modal('show');
                    },
                    error: function (error) {
                        alert(error);
                    }
                });
            }
        });
    });

</script>

DeltaQrCode/Views/Hotel/_HotelList.cshtml
@using DeltaQrCode.HelpersAndExtensions
@using System.Security.Claims
@model DeltaQrCode.ViewModels.HotelListViewModel


<div class="row justify-content-center">
    <div class="col-auto">
        <table class="table table-responsive table-sm table-responsive-md table-responsive-sm table-bordered table-hover">
            <thead>
                <tr class="text-center">
                    <th style="" scope="col">Actiune</th>
                    <th scope="col">Client/Flota</th>
                    <th scope="col">Nr. Telefon</th>
                    <th scope="col">Nr. Auto</th>
                    <th scope="col">Serie Sasiu</th>
                    <th scope="col">Set</th>

                    <th style="min-width:100px;" scope="col">Poz</th>
                    @*<th scope="col">Status Curent</th>*@
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.List)
                {
                    <tr class="text-center">
                        <td class="flex-row">
                            <div class="col-md-12">
                                <div class="btn btn-outline-info btn-sm infoButton" type="button" data-value="@item.SetAnvelope.Id" data-actionType="info"><i class="fas fa-info-circle "></i></div>
                            </div>
                            <div class="col-md-12">

                                <a class="btn btn-outline-warning btn-sm" type="button" asp-action="EditSetAnv" asp-controller="Hotel" asp-route-id="@item.SetAnvelope.Id" asp-route-actionType="edit"><i class="fas fa-pencil-alt"></i></a>
                            </div>
                            @if (User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value == "admin")
                            {
                                <div class="col-md-12">
                                    <div class="btn btn-outline-danger btn-sm deleteButton" type="button" data-value="@item.SetAnvelope.Id"><i class="fas fa-trash-alt"></i></div>
                                </div>
                            }
                        </td>
                        <td>@item.Client.NumeClient</td>
                        <td>@item.Client.NumarTelefon</td>
                        <td>@item.Masina.NumarInmatriculare</td>
                        <td>@item.Masina.SerieSasiu</td>
                        <td>@item.SetAnvelope.NumeSet</td>
                        <td style="white-space:pre-line" ;>@item.SetAnvelope.PozitieSet</td>
                        @*@{
                                string color = "#ff4242";
                                if (item.Anvelopa.StatusCurent == StatusAnvelope.InRaft.ToDisplayString())
                                {
                                    color = "lightgreen";
                                }
                                else if (item.Anvelopa.StatusCurent == StatusAnvelope.Montate.ToDisplayString())
                                {
                                    color = "yellow";
                                }
                                else if (item.Anvelopa.StatusCurent == StatusAnvelope.Predate.ToDisplayString())
                                {
                                    color = "#ff7b42";
                                }
                                <td style="background-color: @color">
                                    @item.Anvelopa.StatusCurent
                                </td>
                            }*@
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<div hidden="hidden" id="hasPrev" data-value="@Model.List.HasPreviousPage.ToString().ToLower()"></div>
<div hidden="hidden" id="hasNext" data-value="@Model.List.HasNextPage.ToString().ToLower()"></div>


<div class="text-center">
    <button id="buttonPrev" data-pageNumber="@(Model.List.PageIndex - 1)"
            class=" customPagination btn btn-default">
        Previous
    </button>
    <button id="buttonNext" data-pageNumber="@(Model.List.PageIndex + 1)"
            class=" customPagination btn btn-default">
        Next
    </button>
</div>